name: Build Repo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install --legacy-peer-deps
    - name: Run Unit Test
      run: npm run test
